### ISSUE TITLE
Checkbox not rendering

### ISSUE THREAD

**Issue by svenjacobs** [sephiroth74/Tri-State-Checkbox#1]
Tried out your library but unfortunately the checkbox is not rendered. When I add the `android:text` attribute I can see the text label but no checkbox. This is on a project with min SDK 23.

**Comment by ricovivid** [comment]
Kind of the same situation. I ran it in an emulator and the app kept crashing. When I looked at logcat I noticed that it couldn't resolve the reference to Timber, so I added it. After I added it the checkbox in the preview disappeared but the app runs now, obviously without a checkbox.

**Comment by svenjacobs** [comment]
_imho_ a library should not have a hard dependency on a logging framework like Timber. But it seems this is not the root of the problem...

**Comment by ricovivid** [comment]
@svenjacobs when you remove the `android:text` does the checkbox appear? I had a rough time even building and running the solution after I added this library. Up until the time that I added the dependency for Timber like I mentioned before.

**Comment by svenjacobs** [comment]
@innov83r No, the checkbox does not appear with our without the `text` attribute.

**Comment by ricovivid** [comment]
@svenjacobs did you have issues installing and building this library? Because I did.

**Comment by ricovivid** [comment]
@sephiroth74 which installation instruction set is the correct one?

1. [The README on your github repo](https://github.com/sephiroth74/Tri-State-Checkbox#installation)
2. [The instructions at The Android Arsenal](https://android-arsenal.com/details/1/7470#!package)

**Comment by svenjacobs** [comment]
> did you have issues installing and building this library

No, I didn't. I didn't even notice that the library depends on Timber. Timber is a transitive dependency so I wonder why it didn't work for you? Unless you have some special Gradle configuration?

**Comment by innov83r** [comment]
This is the error I get in LogCat when I open the app I'm working on:

`2020-02-27 14:49:01.800 14357-14357/com.software.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.software.test, PID: 14357
    java.lang.NoClassDefFoundError: Failed resolution of: Ltimber/log/Timber;
        at it.sephiroth.android.library.checkbox3state.CheckBox3.<clinit>(CheckBox3.java:19)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
    	at androidx.`

**Comment by ricovivid** [comment]
> > did you have issues installing and building this library
> 
> No, I didn't. I didn't even notice that the library depends on Timber. Timber is a transitive dependency so I wonder why it didn't work for you? Unless you have some special Gradle configuration?

It didn't work because I had the '@aar' suffix on my dependency. I removed it and it let me build. I also started playing around with it a bit and was able to get a checkbox by explicitly showing one via the drawables resource. I'm going to work on implementing the kotlin code to see if I can get it to be selectable. I'll post once I have more news.

**Comment by ricovivid** [comment]
I spent some time this weekend and I was able to get a checkbox to display by putting this in my main activity: checkBox1.setChecked(false, false). Without that line I looks like text gets rendered but not the checkbox.

**Comment by cschiefe** [comment]
I'm also having difficulty with the checkbox not rendering, even with innov83r's Mar 1 suggestion, even in a completely vanilla project in Android Studio. The install was easy with the android-arsenal instructions.

My Gradle file, for a Java project, SDK <= 28, has:
`   implementation 'com.github.sephiroth74:Tri-State-Checkbox:v1.0.0'`

**For me what fixed it was making sure to include the style attribute in the layout:**
`    <it.sephiroth.android.library.checkbox3state.CheckBox3`
`        android:id="@+id/cb"`
`        style="@style/Sephiroth.Widget.Checkbox3"`

**Sadly, it's still not rendering in my own app...**

**Comment by 000407** [comment]
Apparently, adding `style="@style/Sephiroth.Widget.Checkbox3"` in the XML layout definition fixes the issue...
